import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getCurrentSession } from "../../auth";
import { ThemeProvider } from "@/contexts/themeProvider";
import SessionProvider from "@/contexts/sessionProvider";
import Header from "@/components/layout/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getCurrentSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <SessionProvider session={session}>
            <Header session={session} />
            {children}
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
