import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/contexts/themeProvider";
import SessionProvider from "@/contexts/sessionProvider";
import { ReduxProvider } from "@/contexts/reduxProvider";
import { getCurrentSession } from "../../auth";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getCurrentSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <ReduxProvider>
            <SessionProvider session={session}>
              <Toaster richColors />

              <div className="min-h-[var(--container-height)] w-full">
                {children}
              </div>
            </SessionProvider>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
