import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/contexts/themeProvider";
import SessionProvider from "@/contexts/sessionProvider";
import { getCurrentSession } from "../../auth";
import Header from "@/components/layout/header/header";
import Footer from "@/components/layout/footer/footer";
import { Toaster } from "@/contexts/toasterProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getCurrentSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <SessionProvider session={session}>
            <Toaster richColors />
            <Header />
            <div className="min-h-[var(--container-height)] w-full">
              {children}
            </div>
            <Footer />
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
